package gui;


import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;


public class AdministradordeTareas extends javax.swing.JFrame {
    
    DefaultTableModel mt;
    String[] enc={"     Procesos"};
    String[][] datos=null;
   
         
    public AdministradordeTareas() {
       initComponents();
       this.setLocationRelativeTo(null);
       procesos.setFocusable(false);
       mt= new DefaultTableModel(datos,enc);     
       this.jTable2.setModel(mt); 
     }
public static List listRunningProcesses() {
List<String> processes = new ArrayList<String>();
try {
String line;
Process p = Runtime.getRuntime().exec("tasklist.exe /nh");
BufferedReader input = new BufferedReader
(new InputStreamReader(p.getInputStream()));
while ((line = input.readLine()) != null) {
if (!line.trim().equals("")) {

processes.add(line.substring(0, line.indexOf(" ")));
    }

}
input.close();
    }
        catch (Exception err) {
        err.printStackTrace();
}
        return processes;
}
    void LimpiarTabla(){
        int a =mt.getRowCount()-1;  //Índices van de 0 a n-1
            for(int i=a;i>=0;i--){  
            mt.removeRow(i);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        panelRound1 = new org.edisoncor.gui.panel.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonTask2 = new org.edisoncor.gui.button.ButtonTask();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        procesos = new org.edisoncor.gui.textField.TextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNice1.setBackground(new java.awt.Color(204, 204, 204));

        panelRound1.setForeground(new java.awt.Color(204, 204, 204));
        panelRound1.setColorPrimario(new java.awt.Color(204, 204, 204));
        panelRound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound1MouseClicked(evt);
            }
        });

        jTable2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jTable2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "PROCESOS"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRADOR DE TAREAS");

        buttonTask2.setBackground(new java.awt.Color(0, 0, 0));
        buttonTask2.setForeground(new java.awt.Color(255, 255, 255));
        buttonTask2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utiles/check.fw.png"))); // NOI18N
        buttonTask2.setText(" ");
        buttonTask2.setCategorySmallFont(new Font("Tahoma", Font.BOLD, 18)); // NOI18N
        buttonTask2.setDescription("Mostrar Procesos");
        buttonTask2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTask2ActionPerformed(evt);
            }
        });

        labelMetric1.setText("NUM. DE PROCESOS");
        labelMetric1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        procesos.setForeground(new java.awt.Color(102, 0, 51));
        procesos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        procesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procesosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1Layout.setHorizontalGroup(
        	panelRound1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(panelRound1Layout.createSequentialGroup()
        			.addContainerGap(33, Short.MAX_VALUE)
        			.addComponent(buttonTask2, GroupLayout.PREFERRED_SIZE, 275, GroupLayout.PREFERRED_SIZE)
        			.addGap(22))
        		.addGroup(panelRound1Layout.createSequentialGroup()
        			.addGap(46)
        			.addComponent(labelMetric1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(procesos, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(51, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, panelRound1Layout.createSequentialGroup()
        			.addGap(51)
        			.addGroup(panelRound1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel1)
        				.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(52, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
        	panelRound1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelRound1Layout.createSequentialGroup()
        			.addGap(30)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 382, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(buttonTask2, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(panelRound1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(labelMetric1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(procesos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(58, Short.MAX_VALUE))
        );
        panelRound1.setLayout(panelRound1Layout);

        javax.swing.GroupLayout panelNice1Layout = new javax.swing.GroupLayout(panelNice1);
        panelNice1Layout.setHorizontalGroup(
        	panelNice1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, panelNice1Layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(panelRound1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        panelNice1Layout.setVerticalGroup(
        	panelNice1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, panelNice1Layout.createSequentialGroup()
        			.addContainerGap(28, Short.MAX_VALUE)
        			.addComponent(panelRound1, GroupLayout.PREFERRED_SIZE, 641, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        panelNice1.setLayout(panelNice1Layout);

        getContentPane().add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 680));

        pack();
    }// </editor-fold>                        

    private void panelRound1MouseClicked(java.awt.event.MouseEvent evt) {                                         

    }                                        

    private void procesosMouseClicked(java.awt.event.MouseEvent evt) {                                      

    }                                     

    private void buttonTask2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        LimpiarTabla();
        List<String> processes = listRunningProcesses();
        String result = "";
        Iterator<String> it = processes.iterator();
        int i = 0;
        this.procesos.setText(String.valueOf(processes.size()));
        while (it.hasNext()) {
            result += it.next();
            i++;
            if (i==1) {
                Object[] s={result};
                mt.addRow(s);
                result="";
                i = 0;
            }
        }
    }                                           

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {                                     

    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradordeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradordeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradordeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradordeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradordeTareas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private org.edisoncor.gui.button.ButtonTask buttonTask2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.panel.PanelRound panelRound1;
    private org.edisoncor.gui.textField.TextFieldRound procesos;
    // End of variables declaration                   
}
